version: "3.8"

services:
  client:
    build:
      context: ./
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.cld.loadbalancer.server.port=80

      - traefik.http.routers.cld.service=cld@docker
      - traefik.http.routers.cld.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.cld.entrypoints=web
      - traefik.http.routers.cld.middlewares=redirect-https

      - traefik.http.routers.cld-secured.service=cld@docker
      - traefik.http.routers.cld-secured.entrypoints=web-secured
      - traefik.http.routers.cld-secured.tls=true
      - traefik.http.routers.cld-secured.rule=Host(`${APP_DOMAIN}`)

networks:
  proxy:
    external: true
